{% set name = "SRW" %}
{% set version = "2020.06.05" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ochubar/{{ name }}
  # commit https://github.com/ochubar/SRW/commit/d8eea70243caa7cb55bab61be65bf6dbfbc2c1b0
  git_rev: d8eea70243caa7cb55bab61be65bf6dbfbc2c1b0
  patches:
    - compilers.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy
    - pillow
    - scipy

test:
  imports:
    - srwl_bl
    - srwlib
    - srwlpy

about:
  home: https://github.com/ochubar/SRW
  license: Custom
  license_url: https://github.com/ochubar/SRW/blob/master/COPYRIGHT.txt
  summary: Synchrotron Radiation Workshop
