{% set name = "SRW" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ochubar/{{ name }}
  git_rev: d6c5f7ebfea3954e0863755209b4b249355c59c3
  patches:
    - compilers.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - matplotlib
    - numpy
    - pillow
    - scipy

test:
  imports:
    - srwl_bl
    - srwlib
    - srwlpy

about:
  home: https://github.com/ochubar/SRW
  license: Custom
  license_url: https://github.com/ochubar/SRW/blob/master/COPYRIGHT.txt
  summary: Synchrotron Radiation Workshop
