github:
  user_or_org: nsls-ii-forge
channels:
  sources:
    - nsls2forge
    - defaults
  targets:
    - [nsls2forge, main]
azure:
  user_or_org: nsls2forge
  project_name: nsls2forge
provider:
  linux: azure
  osx: azure
  win: azure
upload_on_branch: master
